packages:
  - apps/*
  - packages/**/*
catalog:
  react: ">=19"
  react-dom: ">=19"
  next: ">=15"
  motion: ">=12"
  "@types/react": ">=19"
  "@types/react-dom": ">=19"
  tailwindcss: ^4.1.4
  typescript: 5.8.3
  "@floating-ui/react": ">=0.27"
  "@tanstack/react-table": ">=8"
onlyBuiltDependencies:
  - esbuild
  - sharp
